FROM clonedeploy/clonedeploy:latest
LABEL org.freenas.interactive="false" \
      org.freenas.version="0" \
      org.freenas.upgradeable="false" \
      org.freenas.expose-ports-at-host="true" \
      org.freenas.autostart="false" \
      org.freenas.web-ui-protocol="http" \
      org.freenas.web-ui-port="80" \
      org.freenas.web-ui-path="" \
      org.freenas.volumes="[						\
          {								\
              \"name\": \"/var/www/html\",				\
              \"descr\": \"CloneDeploy persistent data volume\"		\
          }								\
      ]" 